# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-02 18:03
from __future__ import unicode_literals

from django.db import migrations, models
import location_field.models.plain


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sighting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sighter', models.CharField(help_text='Who saw the Lyle?', max_length=200)),
                ('description', models.TextField()),
                ('datetime', models.DateTimeField(verbose_name='date and time seen')),
                ('url', models.CharField(max_length=250, verbose_name='URL')),
                ('city', models.CharField(blank=True, max_length=255, null=True)),
                ('location', location_field.models.plain.PlainLocationField(max_length=63)),
            ],
        ),
    ]
