# Generated by Django 2.0 on 2018-01-18 21:13

from django.db import migrations
import location_field.models.plain


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20180118_2113'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sighting',
            name='location',
            field=location_field.models.plain.PlainLocationField(blank=True, max_length=63, null=True),
        ),
    ]
