# Generated by Django 2.0 on 2018-01-19 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20180118_2113'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sighting',
            name='url',
            field=models.CharField(max_length=250, unique=True, verbose_name='URL'),
        ),
    ]
