# Generated by Django 2.0.3 on 2018-03-25 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_sighting_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Spotter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('instagram_id', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='sighting',
            name='photo',
            field=models.ImageField(null=True, upload_to='sighting-photos'),
        ),
    ]
