# Generated by Django 2.0.3 on 2018-03-25 14:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20180325_1401'),
    ]

    operations = [
        migrations.AddField(
            model_name='sighting',
            name='spotter',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.Spotter'),
        ),
    ]
